### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by PeterDaveHello**
To use "Markdown" style, not html.

### CODE REVIEW

**Comment by keicheng** [comment]
ok, i just copy and paste, not use markdown, wait me

**Comment by PeterDaveHello** [comment]
???

**Comment by keicheng** [comment]
wow, You edited?  thanks!!!!!

**Comment by PeterDaveHello** [comment]
I think you can just merge it.

**Comment by PeterDaveHello** [comment]
All done.

**Comment by PeterDaveHello** [comment]
All done, I think you can just merge it.

**Comment by keicheng** [comment]
Thanks!!!

**Comment by keicheng** [comment]
I`ll study markdown

**Pull request merged**
